dist: bionic

before_install:
  - wget https://packages.chef.io/files/stable/chef-workstation/21.10.640/ubuntu/18.04/chef-workstation_21.10.640-1_amd64.deb
  - sudo dpkg -i chef-workstation_21.10.640-1_amd64.deb
  - chef --version

install: echo "skip bundle install"

branches:
  only:
  - master
  - /^feature-.*$/

env:
  matrix:
  - INSTANCE=default-ubuntu-1804

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(/opt/chef-workstation/bin/chef shell-init bash)"
- /opt/chef-workstation/bin/chef exec rake tests

script:
- /opt/chef-workstation/embedded/bin/kitchen verify ${INSTANCE}

after_script:
- /opt/chef-workstation/embedded/bin/kitchen destroy ${INSTANCE}
