name 'python_setup'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'Apache-2.0'
description 'Installs/Configures python_setup'
chef_version '>= 16.0'
supports 'ubuntu', '= 18.04'
source_url 'https://github.com/EagleGenomics-cookbooks/python_setup'
issues_url 'https://github.com/EagleGenomics-cookbooks/python_setup/issues'
version '0.0.7'

depends 'pyenv'
